//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5477.
// 
#pragma warning disable 1591

namespace TestServices.WSTH {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="THServiceSoap", Namespace="http://tempuri.org/")]
    public partial class THService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback W_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback payW_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPay_BillOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemHDThuOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemHDChuyenOperationCompleted;
        
        private System.Threading.SendOrPostCallback KiemTraHDThuOperationCompleted;
        
        private System.Threading.SendOrPostCallback KiemTraDongNuocOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public THService() {
            this.Url = global::TestServices.Properties.Settings.Default.TestServices_WSTH_THService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCustomerInfoCompletedEventHandler getCustomerInfoCompleted;
        
        /// <remarks/>
        public event W_BillCompletedEventHandler W_BillCompleted;
        
        /// <remarks/>
        public event payW_BillCompletedEventHandler payW_BillCompleted;
        
        /// <remarks/>
        public event checkPay_BillCompletedEventHandler checkPay_BillCompleted;
        
        /// <remarks/>
        public event ThemHDThuCompletedEventHandler ThemHDThuCompleted;
        
        /// <remarks/>
        public event ThemHDChuyenCompletedEventHandler ThemHDChuyenCompleted;
        
        /// <remarks/>
        public event KiemTraHDThuCompletedEventHandler KiemTraHDThuCompleted;
        
        /// <remarks/>
        public event KiemTraDongNuocCompletedEventHandler KiemTraDongNuocCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerInfo(string db, string ten, string matkhau) {
            object[] results = this.Invoke("getCustomerInfo", new object[] {
                        db,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string db, string ten, string matkhau) {
            this.getCustomerInfoAsync(db, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string db, string ten, string matkhau, object userState) {
            if ((this.getCustomerInfoOperationCompleted == null)) {
                this.getCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("getCustomerInfo", new object[] {
                        db,
                        ten,
                        matkhau}, this.getCustomerInfoOperationCompleted, userState);
        }
        
        private void OngetCustomerInfoOperationCompleted(object arg) {
            if ((this.getCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInfoCompleted(this, new getCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/W_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet W_Bill(string db, string ten, string matkhau) {
            object[] results = this.Invoke("W_Bill", new object[] {
                        db,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void W_BillAsync(string db, string ten, string matkhau) {
            this.W_BillAsync(db, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void W_BillAsync(string db, string ten, string matkhau, object userState) {
            if ((this.W_BillOperationCompleted == null)) {
                this.W_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnW_BillOperationCompleted);
            }
            this.InvokeAsync("W_Bill", new object[] {
                        db,
                        ten,
                        matkhau}, this.W_BillOperationCompleted, userState);
        }
        
        private void OnW_BillOperationCompleted(object arg) {
            if ((this.W_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.W_BillCompleted(this, new W_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payW_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool payW_Bill(string id, string ten, string matkhau) {
            object[] results = this.Invoke("payW_Bill", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void payW_BillAsync(string id, string ten, string matkhau) {
            this.payW_BillAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void payW_BillAsync(string id, string ten, string matkhau, object userState) {
            if ((this.payW_BillOperationCompleted == null)) {
                this.payW_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpayW_BillOperationCompleted);
            }
            this.InvokeAsync("payW_Bill", new object[] {
                        id,
                        ten,
                        matkhau}, this.payW_BillOperationCompleted, userState);
        }
        
        private void OnpayW_BillOperationCompleted(object arg) {
            if ((this.payW_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.payW_BillCompleted(this, new payW_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkPay_Bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet checkPay_Bill(string id, string ten, string matkhau) {
            object[] results = this.Invoke("checkPay_Bill", new object[] {
                        id,
                        ten,
                        matkhau});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void checkPay_BillAsync(string id, string ten, string matkhau) {
            this.checkPay_BillAsync(id, ten, matkhau, null);
        }
        
        /// <remarks/>
        public void checkPay_BillAsync(string id, string ten, string matkhau, object userState) {
            if ((this.checkPay_BillOperationCompleted == null)) {
                this.checkPay_BillOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPay_BillOperationCompleted);
            }
            this.InvokeAsync("checkPay_Bill", new object[] {
                        id,
                        ten,
                        matkhau}, this.checkPay_BillOperationCompleted, userState);
        }
        
        private void OncheckPay_BillOperationCompleted(object arg) {
            if ((this.checkPay_BillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPay_BillCompleted(this, new checkPay_BillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemHDThu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemHDThu(string SoHoaDon, string DanhBo, int Nam, int Ky, int SoTien, string TenDichVu, string TenNganHang) {
            object[] results = this.Invoke("ThemHDThu", new object[] {
                        SoHoaDon,
                        DanhBo,
                        Nam,
                        Ky,
                        SoTien,
                        TenDichVu,
                        TenNganHang});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemHDThuAsync(string SoHoaDon, string DanhBo, int Nam, int Ky, int SoTien, string TenDichVu, string TenNganHang) {
            this.ThemHDThuAsync(SoHoaDon, DanhBo, Nam, Ky, SoTien, TenDichVu, TenNganHang, null);
        }
        
        /// <remarks/>
        public void ThemHDThuAsync(string SoHoaDon, string DanhBo, int Nam, int Ky, int SoTien, string TenDichVu, string TenNganHang, object userState) {
            if ((this.ThemHDThuOperationCompleted == null)) {
                this.ThemHDThuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemHDThuOperationCompleted);
            }
            this.InvokeAsync("ThemHDThu", new object[] {
                        SoHoaDon,
                        DanhBo,
                        Nam,
                        Ky,
                        SoTien,
                        TenDichVu,
                        TenNganHang}, this.ThemHDThuOperationCompleted, userState);
        }
        
        private void OnThemHDThuOperationCompleted(object arg) {
            if ((this.ThemHDThuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemHDThuCompleted(this, new ThemHDThuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemHDChuyen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemHDChuyen(string SoHoaDon, string DanhBo, int Nam, int Ky, int SoTien, string TenDichVu, string TenNganHang) {
            object[] results = this.Invoke("ThemHDChuyen", new object[] {
                        SoHoaDon,
                        DanhBo,
                        Nam,
                        Ky,
                        SoTien,
                        TenDichVu,
                        TenNganHang});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemHDChuyenAsync(string SoHoaDon, string DanhBo, int Nam, int Ky, int SoTien, string TenDichVu, string TenNganHang) {
            this.ThemHDChuyenAsync(SoHoaDon, DanhBo, Nam, Ky, SoTien, TenDichVu, TenNganHang, null);
        }
        
        /// <remarks/>
        public void ThemHDChuyenAsync(string SoHoaDon, string DanhBo, int Nam, int Ky, int SoTien, string TenDichVu, string TenNganHang, object userState) {
            if ((this.ThemHDChuyenOperationCompleted == null)) {
                this.ThemHDChuyenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemHDChuyenOperationCompleted);
            }
            this.InvokeAsync("ThemHDChuyen", new object[] {
                        SoHoaDon,
                        DanhBo,
                        Nam,
                        Ky,
                        SoTien,
                        TenDichVu,
                        TenNganHang}, this.ThemHDChuyenOperationCompleted, userState);
        }
        
        private void OnThemHDChuyenOperationCompleted(object arg) {
            if ((this.ThemHDChuyenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemHDChuyenCompleted(this, new ThemHDChuyenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KiemTraHDThu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KiemTraHDThu(string DanhBo, int Nam, int Ky) {
            object[] results = this.Invoke("KiemTraHDThu", new object[] {
                        DanhBo,
                        Nam,
                        Ky});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KiemTraHDThuAsync(string DanhBo, int Nam, int Ky) {
            this.KiemTraHDThuAsync(DanhBo, Nam, Ky, null);
        }
        
        /// <remarks/>
        public void KiemTraHDThuAsync(string DanhBo, int Nam, int Ky, object userState) {
            if ((this.KiemTraHDThuOperationCompleted == null)) {
                this.KiemTraHDThuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKiemTraHDThuOperationCompleted);
            }
            this.InvokeAsync("KiemTraHDThu", new object[] {
                        DanhBo,
                        Nam,
                        Ky}, this.KiemTraHDThuOperationCompleted, userState);
        }
        
        private void OnKiemTraHDThuOperationCompleted(object arg) {
            if ((this.KiemTraHDThuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KiemTraHDThuCompleted(this, new KiemTraHDThuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KiemTraDongNuoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KiemTraDongNuoc(string DanhBo, out int PhiMoNuoc) {
            object[] results = this.Invoke("KiemTraDongNuoc", new object[] {
                        DanhBo});
            PhiMoNuoc = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KiemTraDongNuocAsync(string DanhBo) {
            this.KiemTraDongNuocAsync(DanhBo, null);
        }
        
        /// <remarks/>
        public void KiemTraDongNuocAsync(string DanhBo, object userState) {
            if ((this.KiemTraDongNuocOperationCompleted == null)) {
                this.KiemTraDongNuocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKiemTraDongNuocOperationCompleted);
            }
            this.InvokeAsync("KiemTraDongNuoc", new object[] {
                        DanhBo}, this.KiemTraDongNuocOperationCompleted, userState);
        }
        
        private void OnKiemTraDongNuocOperationCompleted(object arg) {
            if ((this.KiemTraDongNuocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KiemTraDongNuocCompleted(this, new KiemTraDongNuocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void getCustomerInfoCompletedEventHandler(object sender, getCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void W_BillCompletedEventHandler(object sender, W_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class W_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal W_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void payW_BillCompletedEventHandler(object sender, payW_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class payW_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal payW_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void checkPay_BillCompletedEventHandler(object sender, checkPay_BillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPay_BillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPay_BillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ThemHDThuCompletedEventHandler(object sender, ThemHDThuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemHDThuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemHDThuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ThemHDChuyenCompletedEventHandler(object sender, ThemHDChuyenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemHDChuyenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemHDChuyenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void KiemTraHDThuCompletedEventHandler(object sender, KiemTraHDThuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KiemTraHDThuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KiemTraHDThuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void KiemTraDongNuocCompletedEventHandler(object sender, KiemTraDongNuocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KiemTraDongNuocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KiemTraDongNuocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int PhiMoNuoc {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591