#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THService.LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="KTKS_DonKH")]
	public partial class KinhDoanhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTCTDB(CTCTDB instance);
    partial void UpdateCTCTDB(CTCTDB instance);
    partial void DeleteCTCTDB(CTCTDB instance);
    partial void InsertCTCHDB(CTCHDB instance);
    partial void UpdateCTCHDB(CTCHDB instance);
    partial void DeleteCTCHDB(CTCHDB instance);
    #endregion
		
		public KinhDoanhDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KTKS_DonKHConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KinhDoanhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KinhDoanhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KinhDoanhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KinhDoanhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTCTDB> CTCTDBs
		{
			get
			{
				return this.GetTable<CTCTDB>();
			}
		}
		
		public System.Data.Linq.Table<CTCHDB> CTCHDBs
		{
			get
			{
				return this.GetTable<CTCHDB>();
			}
		}
	}
	
	[Table(Name="dbo.CTCTDB")]
	public partial class CTCTDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _MaCTCTDB;
		
		private string _DanhBo;
		
		private string _HopDong;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _Dot;
		
		private string _Ky;
		
		private string _Nam;
		
		private string _LyDo;
		
		private string _GhiChuLyDo;
		
		private System.Nullable<int> _SoTien;
		
		private string _NoiDung;
		
		private bool _TCTBXuLy;
		
		private bool _TroNgai;
		
		private System.Nullable<System.DateTime> _NgayXuLy;
		
		private string _NoiDungXuLy;
		
		private System.Nullable<System.DateTime> _CreateDate_NgayXuLy;
		
		private System.Nullable<System.DateTime> _NgayTCTBXuLy;
		
		private string _KetQuaTCTBXuLy;
		
		private bool _CapTrenXuLy;
		
		private System.Nullable<System.DateTime> _NgayCapTrenXuLy;
		
		private string _KetQuaCapTrenXuLy;
		
		private System.Nullable<int> _ThoiGianLapCatHuy;
		
		private System.Nullable<decimal> _MaCHDB;
		
		private string _NoiNhan;
		
		private string _NguoiKy;
		
		private string _ChucVu;
		
		private bool _ThongBaoDuocKy;
		
		private bool _DaLapPhieu;
		
		private System.Nullable<decimal> _SoPhieu;
		
		private System.Nullable<System.DateTime> _NgayLapPhieu;
		
		private bool _PhieuDuocKy;
		
		private string _HieuLucKy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private bool _ThuTien_Nhan;
		
		private System.Nullable<System.DateTime> _ThuTien_NgayNhan;
		
		private string _ThuTien_GhiChu;
		
		private bool _DocSo_Nhan;
		
		private System.Nullable<System.DateTime> _DocSo_NgayNhan;
		
		private string _DocSo_GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTCTDBChanging(decimal value);
    partial void OnMaCTCTDBChanged();
    partial void OnDanhBoChanging(string value);
    partial void OnDanhBoChanged();
    partial void OnHopDongChanging(string value);
    partial void OnHopDongChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDotChanging(string value);
    partial void OnDotChanged();
    partial void OnKyChanging(string value);
    partial void OnKyChanged();
    partial void OnNamChanging(string value);
    partial void OnNamChanged();
    partial void OnLyDoChanging(string value);
    partial void OnLyDoChanged();
    partial void OnGhiChuLyDoChanging(string value);
    partial void OnGhiChuLyDoChanged();
    partial void OnSoTienChanging(System.Nullable<int> value);
    partial void OnSoTienChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnTCTBXuLyChanging(bool value);
    partial void OnTCTBXuLyChanged();
    partial void OnTroNgaiChanging(bool value);
    partial void OnTroNgaiChanged();
    partial void OnNgayXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuLyChanged();
    partial void OnNoiDungXuLyChanging(string value);
    partial void OnNoiDungXuLyChanged();
    partial void OnCreateDate_NgayXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDate_NgayXuLyChanged();
    partial void OnNgayTCTBXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTCTBXuLyChanged();
    partial void OnKetQuaTCTBXuLyChanging(string value);
    partial void OnKetQuaTCTBXuLyChanged();
    partial void OnCapTrenXuLyChanging(bool value);
    partial void OnCapTrenXuLyChanged();
    partial void OnNgayCapTrenXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapTrenXuLyChanged();
    partial void OnKetQuaCapTrenXuLyChanging(string value);
    partial void OnKetQuaCapTrenXuLyChanged();
    partial void OnThoiGianLapCatHuyChanging(System.Nullable<int> value);
    partial void OnThoiGianLapCatHuyChanged();
    partial void OnMaCHDBChanging(System.Nullable<decimal> value);
    partial void OnMaCHDBChanged();
    partial void OnNoiNhanChanging(string value);
    partial void OnNoiNhanChanged();
    partial void OnNguoiKyChanging(string value);
    partial void OnNguoiKyChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnThongBaoDuocKyChanging(bool value);
    partial void OnThongBaoDuocKyChanged();
    partial void OnDaLapPhieuChanging(bool value);
    partial void OnDaLapPhieuChanged();
    partial void OnSoPhieuChanging(System.Nullable<decimal> value);
    partial void OnSoPhieuChanged();
    partial void OnNgayLapPhieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapPhieuChanged();
    partial void OnPhieuDuocKyChanging(bool value);
    partial void OnPhieuDuocKyChanged();
    partial void OnHieuLucKyChanging(string value);
    partial void OnHieuLucKyChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    partial void OnThuTien_NhanChanging(bool value);
    partial void OnThuTien_NhanChanged();
    partial void OnThuTien_NgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnThuTien_NgayNhanChanged();
    partial void OnThuTien_GhiChuChanging(string value);
    partial void OnThuTien_GhiChuChanged();
    partial void OnDocSo_NhanChanging(bool value);
    partial void OnDocSo_NhanChanged();
    partial void OnDocSo_NgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnDocSo_NgayNhanChanged();
    partial void OnDocSo_GhiChuChanging(string value);
    partial void OnDocSo_GhiChuChanged();
    #endregion
		
		public CTCTDB()
		{
			OnCreated();
		}
		
		[Column(Storage="_MaCTCTDB", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal MaCTCTDB
		{
			get
			{
				return this._MaCTCTDB;
			}
			set
			{
				if ((this._MaCTCTDB != value))
				{
					this.OnMaCTCTDBChanging(value);
					this.SendPropertyChanging();
					this._MaCTCTDB = value;
					this.SendPropertyChanged("MaCTCTDB");
					this.OnMaCTCTDBChanged();
				}
			}
		}
		
		[Column(Storage="_DanhBo", DbType="NVarChar(11)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this.OnDanhBoChanging(value);
					this.SendPropertyChanging();
					this._DanhBo = value;
					this.SendPropertyChanged("DanhBo");
					this.OnDanhBoChanged();
				}
			}
		}
		
		[Column(Storage="_HopDong", DbType="NVarChar(50)")]
		public string HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					this.OnHopDongChanging(value);
					this.SendPropertyChanging();
					this._HopDong = value;
					this.SendPropertyChanged("HopDong");
					this.OnHopDongChanged();
				}
			}
		}
		
		[Column(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[Column(Storage="_Dot", DbType="NVarChar(50)")]
		public string Dot
		{
			get
			{
				return this._Dot;
			}
			set
			{
				if ((this._Dot != value))
				{
					this.OnDotChanging(value);
					this.SendPropertyChanging();
					this._Dot = value;
					this.SendPropertyChanged("Dot");
					this.OnDotChanged();
				}
			}
		}
		
		[Column(Storage="_Ky", DbType="NVarChar(50)")]
		public string Ky
		{
			get
			{
				return this._Ky;
			}
			set
			{
				if ((this._Ky != value))
				{
					this.OnKyChanging(value);
					this.SendPropertyChanging();
					this._Ky = value;
					this.SendPropertyChanged("Ky");
					this.OnKyChanged();
				}
			}
		}
		
		[Column(Storage="_Nam", DbType="NVarChar(50)")]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[Column(Storage="_LyDo", DbType="NVarChar(MAX)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this.OnLyDoChanging(value);
					this.SendPropertyChanging();
					this._LyDo = value;
					this.SendPropertyChanged("LyDo");
					this.OnLyDoChanged();
				}
			}
		}
		
		[Column(Storage="_GhiChuLyDo", DbType="NVarChar(MAX)")]
		public string GhiChuLyDo
		{
			get
			{
				return this._GhiChuLyDo;
			}
			set
			{
				if ((this._GhiChuLyDo != value))
				{
					this.OnGhiChuLyDoChanging(value);
					this.SendPropertyChanging();
					this._GhiChuLyDo = value;
					this.SendPropertyChanged("GhiChuLyDo");
					this.OnGhiChuLyDoChanged();
				}
			}
		}
		
		[Column(Storage="_SoTien", DbType="Int")]
		public System.Nullable<int> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[Column(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[Column(Storage="_TCTBXuLy", DbType="Bit NOT NULL")]
		public bool TCTBXuLy
		{
			get
			{
				return this._TCTBXuLy;
			}
			set
			{
				if ((this._TCTBXuLy != value))
				{
					this.OnTCTBXuLyChanging(value);
					this.SendPropertyChanging();
					this._TCTBXuLy = value;
					this.SendPropertyChanged("TCTBXuLy");
					this.OnTCTBXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_TroNgai", DbType="Bit NOT NULL")]
		public bool TroNgai
		{
			get
			{
				return this._TroNgai;
			}
			set
			{
				if ((this._TroNgai != value))
				{
					this.OnTroNgaiChanging(value);
					this.SendPropertyChanging();
					this._TroNgai = value;
					this.SendPropertyChanged("TroNgai");
					this.OnTroNgaiChanged();
				}
			}
		}
		
		[Column(Storage="_NgayXuLy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuLy
		{
			get
			{
				return this._NgayXuLy;
			}
			set
			{
				if ((this._NgayXuLy != value))
				{
					this.OnNgayXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayXuLy = value;
					this.SendPropertyChanged("NgayXuLy");
					this.OnNgayXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_NoiDungXuLy", DbType="NVarChar(MAX)")]
		public string NoiDungXuLy
		{
			get
			{
				return this._NoiDungXuLy;
			}
			set
			{
				if ((this._NoiDungXuLy != value))
				{
					this.OnNoiDungXuLyChanging(value);
					this.SendPropertyChanging();
					this._NoiDungXuLy = value;
					this.SendPropertyChanged("NoiDungXuLy");
					this.OnNoiDungXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_CreateDate_NgayXuLy", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate_NgayXuLy
		{
			get
			{
				return this._CreateDate_NgayXuLy;
			}
			set
			{
				if ((this._CreateDate_NgayXuLy != value))
				{
					this.OnCreateDate_NgayXuLyChanging(value);
					this.SendPropertyChanging();
					this._CreateDate_NgayXuLy = value;
					this.SendPropertyChanged("CreateDate_NgayXuLy");
					this.OnCreateDate_NgayXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_NgayTCTBXuLy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTCTBXuLy
		{
			get
			{
				return this._NgayTCTBXuLy;
			}
			set
			{
				if ((this._NgayTCTBXuLy != value))
				{
					this.OnNgayTCTBXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayTCTBXuLy = value;
					this.SendPropertyChanged("NgayTCTBXuLy");
					this.OnNgayTCTBXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_KetQuaTCTBXuLy", DbType="NVarChar(MAX)")]
		public string KetQuaTCTBXuLy
		{
			get
			{
				return this._KetQuaTCTBXuLy;
			}
			set
			{
				if ((this._KetQuaTCTBXuLy != value))
				{
					this.OnKetQuaTCTBXuLyChanging(value);
					this.SendPropertyChanging();
					this._KetQuaTCTBXuLy = value;
					this.SendPropertyChanged("KetQuaTCTBXuLy");
					this.OnKetQuaTCTBXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_CapTrenXuLy", DbType="Bit NOT NULL")]
		public bool CapTrenXuLy
		{
			get
			{
				return this._CapTrenXuLy;
			}
			set
			{
				if ((this._CapTrenXuLy != value))
				{
					this.OnCapTrenXuLyChanging(value);
					this.SendPropertyChanging();
					this._CapTrenXuLy = value;
					this.SendPropertyChanged("CapTrenXuLy");
					this.OnCapTrenXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_NgayCapTrenXuLy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCapTrenXuLy
		{
			get
			{
				return this._NgayCapTrenXuLy;
			}
			set
			{
				if ((this._NgayCapTrenXuLy != value))
				{
					this.OnNgayCapTrenXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayCapTrenXuLy = value;
					this.SendPropertyChanged("NgayCapTrenXuLy");
					this.OnNgayCapTrenXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_KetQuaCapTrenXuLy", DbType="NVarChar(MAX)")]
		public string KetQuaCapTrenXuLy
		{
			get
			{
				return this._KetQuaCapTrenXuLy;
			}
			set
			{
				if ((this._KetQuaCapTrenXuLy != value))
				{
					this.OnKetQuaCapTrenXuLyChanging(value);
					this.SendPropertyChanging();
					this._KetQuaCapTrenXuLy = value;
					this.SendPropertyChanged("KetQuaCapTrenXuLy");
					this.OnKetQuaCapTrenXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_ThoiGianLapCatHuy", DbType="Int")]
		public System.Nullable<int> ThoiGianLapCatHuy
		{
			get
			{
				return this._ThoiGianLapCatHuy;
			}
			set
			{
				if ((this._ThoiGianLapCatHuy != value))
				{
					this.OnThoiGianLapCatHuyChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianLapCatHuy = value;
					this.SendPropertyChanged("ThoiGianLapCatHuy");
					this.OnThoiGianLapCatHuyChanged();
				}
			}
		}
		
		[Column(Storage="_MaCHDB", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaCHDB
		{
			get
			{
				return this._MaCHDB;
			}
			set
			{
				if ((this._MaCHDB != value))
				{
					this.OnMaCHDBChanging(value);
					this.SendPropertyChanging();
					this._MaCHDB = value;
					this.SendPropertyChanged("MaCHDB");
					this.OnMaCHDBChanged();
				}
			}
		}
		
		[Column(Storage="_NoiNhan", DbType="NVarChar(MAX)")]
		public string NoiNhan
		{
			get
			{
				return this._NoiNhan;
			}
			set
			{
				if ((this._NoiNhan != value))
				{
					this.OnNoiNhanChanging(value);
					this.SendPropertyChanging();
					this._NoiNhan = value;
					this.SendPropertyChanged("NoiNhan");
					this.OnNoiNhanChanged();
				}
			}
		}
		
		[Column(Storage="_NguoiKy", DbType="NVarChar(100)")]
		public string NguoiKy
		{
			get
			{
				return this._NguoiKy;
			}
			set
			{
				if ((this._NguoiKy != value))
				{
					this.OnNguoiKyChanging(value);
					this.SendPropertyChanging();
					this._NguoiKy = value;
					this.SendPropertyChanged("NguoiKy");
					this.OnNguoiKyChanged();
				}
			}
		}
		
		[Column(Storage="_ChucVu", DbType="NVarChar(100)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[Column(Storage="_ThongBaoDuocKy", DbType="Bit NOT NULL")]
		public bool ThongBaoDuocKy
		{
			get
			{
				return this._ThongBaoDuocKy;
			}
			set
			{
				if ((this._ThongBaoDuocKy != value))
				{
					this.OnThongBaoDuocKyChanging(value);
					this.SendPropertyChanging();
					this._ThongBaoDuocKy = value;
					this.SendPropertyChanged("ThongBaoDuocKy");
					this.OnThongBaoDuocKyChanged();
				}
			}
		}
		
		[Column(Storage="_DaLapPhieu", DbType="Bit NOT NULL")]
		public bool DaLapPhieu
		{
			get
			{
				return this._DaLapPhieu;
			}
			set
			{
				if ((this._DaLapPhieu != value))
				{
					this.OnDaLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._DaLapPhieu = value;
					this.SendPropertyChanged("DaLapPhieu");
					this.OnDaLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_SoPhieu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_NgayLapPhieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapPhieu
		{
			get
			{
				return this._NgayLapPhieu;
			}
			set
			{
				if ((this._NgayLapPhieu != value))
				{
					this.OnNgayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPhieu = value;
					this.SendPropertyChanged("NgayLapPhieu");
					this.OnNgayLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_PhieuDuocKy", DbType="Bit NOT NULL")]
		public bool PhieuDuocKy
		{
			get
			{
				return this._PhieuDuocKy;
			}
			set
			{
				if ((this._PhieuDuocKy != value))
				{
					this.OnPhieuDuocKyChanging(value);
					this.SendPropertyChanging();
					this._PhieuDuocKy = value;
					this.SendPropertyChanged("PhieuDuocKy");
					this.OnPhieuDuocKyChanged();
				}
			}
		}
		
		[Column(Storage="_HieuLucKy", DbType="NVarChar(50)")]
		public string HieuLucKy
		{
			get
			{
				return this._HieuLucKy;
			}
			set
			{
				if ((this._HieuLucKy != value))
				{
					this.OnHieuLucKyChanging(value);
					this.SendPropertyChanging();
					this._HieuLucKy = value;
					this.SendPropertyChanged("HieuLucKy");
					this.OnHieuLucKyChanged();
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[Column(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[Column(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[Column(Storage="_ThuTien_Nhan", DbType="Bit NOT NULL")]
		public bool ThuTien_Nhan
		{
			get
			{
				return this._ThuTien_Nhan;
			}
			set
			{
				if ((this._ThuTien_Nhan != value))
				{
					this.OnThuTien_NhanChanging(value);
					this.SendPropertyChanging();
					this._ThuTien_Nhan = value;
					this.SendPropertyChanged("ThuTien_Nhan");
					this.OnThuTien_NhanChanged();
				}
			}
		}
		
		[Column(Storage="_ThuTien_NgayNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThuTien_NgayNhan
		{
			get
			{
				return this._ThuTien_NgayNhan;
			}
			set
			{
				if ((this._ThuTien_NgayNhan != value))
				{
					this.OnThuTien_NgayNhanChanging(value);
					this.SendPropertyChanging();
					this._ThuTien_NgayNhan = value;
					this.SendPropertyChanged("ThuTien_NgayNhan");
					this.OnThuTien_NgayNhanChanged();
				}
			}
		}
		
		[Column(Storage="_ThuTien_GhiChu", DbType="NVarChar(MAX)")]
		public string ThuTien_GhiChu
		{
			get
			{
				return this._ThuTien_GhiChu;
			}
			set
			{
				if ((this._ThuTien_GhiChu != value))
				{
					this.OnThuTien_GhiChuChanging(value);
					this.SendPropertyChanging();
					this._ThuTien_GhiChu = value;
					this.SendPropertyChanged("ThuTien_GhiChu");
					this.OnThuTien_GhiChuChanged();
				}
			}
		}
		
		[Column(Storage="_DocSo_Nhan", DbType="Bit NOT NULL")]
		public bool DocSo_Nhan
		{
			get
			{
				return this._DocSo_Nhan;
			}
			set
			{
				if ((this._DocSo_Nhan != value))
				{
					this.OnDocSo_NhanChanging(value);
					this.SendPropertyChanging();
					this._DocSo_Nhan = value;
					this.SendPropertyChanged("DocSo_Nhan");
					this.OnDocSo_NhanChanged();
				}
			}
		}
		
		[Column(Storage="_DocSo_NgayNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> DocSo_NgayNhan
		{
			get
			{
				return this._DocSo_NgayNhan;
			}
			set
			{
				if ((this._DocSo_NgayNhan != value))
				{
					this.OnDocSo_NgayNhanChanging(value);
					this.SendPropertyChanging();
					this._DocSo_NgayNhan = value;
					this.SendPropertyChanged("DocSo_NgayNhan");
					this.OnDocSo_NgayNhanChanged();
				}
			}
		}
		
		[Column(Storage="_DocSo_GhiChu", DbType="NVarChar(MAX)")]
		public string DocSo_GhiChu
		{
			get
			{
				return this._DocSo_GhiChu;
			}
			set
			{
				if ((this._DocSo_GhiChu != value))
				{
					this.OnDocSo_GhiChuChanging(value);
					this.SendPropertyChanging();
					this._DocSo_GhiChu = value;
					this.SendPropertyChanged("DocSo_GhiChu");
					this.OnDocSo_GhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.CTCHDB")]
	public partial class CTCHDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _MaCTCHDB;
		
		private string _DanhBo;
		
		private string _HopDong;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _Dot;
		
		private string _Ky;
		
		private string _Nam;
		
		private string _LyDo;
		
		private string _GhiChuLyDo;
		
		private System.Nullable<int> _SoTien;
		
		private string _NoiDung;
		
		private bool _TCTBXuLy;
		
		private bool _TroNgai;
		
		private bool _CatTam;
		
		private System.Nullable<System.DateTime> _NgayXuLy;
		
		private string _NoiDungXuLy;
		
		private System.Nullable<System.DateTime> _CreateDate_NgayXuLy;
		
		private System.Nullable<System.DateTime> _NgayTCTBXuLy;
		
		private string _KetQuaTCTBXuLy;
		
		private bool _CapTrenXuLy;
		
		private System.Nullable<System.DateTime> _NgayCapTrenXuLy;
		
		private string _KetQuaCapTrenXuLy;
		
		private System.Nullable<int> _ThoiGianLapPhieu;
		
		private bool _DaLapPhieu;
		
		private System.Nullable<decimal> _SoPhieu;
		
		private System.Nullable<System.DateTime> _NgayLapPhieu;
		
		private bool _PhieuDuocKy;
		
		private string _HieuLucKy;
		
		private string _DotLapPhieu;
		
		private string _NguoiKyLapPhieu;
		
		private string _ChucVuLapPhieu;
		
		private bool _DaLapCatTam;
		
		private System.Nullable<decimal> _MaCTCTDB;
		
		private System.Nullable<decimal> _MaCHDB;
		
		private string _NoiNhan;
		
		private string _NguoiKy;
		
		private string _ChucVu;
		
		private bool _ThongBaoDuocKy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private bool _ThuTien_Nhan;
		
		private System.Nullable<System.DateTime> _ThuTien_NgayNhan;
		
		private string _ThuTien_GhiChu;
		
		private bool _DocSo_Nhan;
		
		private System.Nullable<System.DateTime> _DocSo_NgayNhan;
		
		private string _DocSo_GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTCHDBChanging(decimal value);
    partial void OnMaCTCHDBChanged();
    partial void OnDanhBoChanging(string value);
    partial void OnDanhBoChanged();
    partial void OnHopDongChanging(string value);
    partial void OnHopDongChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDotChanging(string value);
    partial void OnDotChanged();
    partial void OnKyChanging(string value);
    partial void OnKyChanged();
    partial void OnNamChanging(string value);
    partial void OnNamChanged();
    partial void OnLyDoChanging(string value);
    partial void OnLyDoChanged();
    partial void OnGhiChuLyDoChanging(string value);
    partial void OnGhiChuLyDoChanged();
    partial void OnSoTienChanging(System.Nullable<int> value);
    partial void OnSoTienChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnTCTBXuLyChanging(bool value);
    partial void OnTCTBXuLyChanged();
    partial void OnTroNgaiChanging(bool value);
    partial void OnTroNgaiChanged();
    partial void OnCatTamChanging(bool value);
    partial void OnCatTamChanged();
    partial void OnNgayXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuLyChanged();
    partial void OnNoiDungXuLyChanging(string value);
    partial void OnNoiDungXuLyChanged();
    partial void OnCreateDate_NgayXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDate_NgayXuLyChanged();
    partial void OnNgayTCTBXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTCTBXuLyChanged();
    partial void OnKetQuaTCTBXuLyChanging(string value);
    partial void OnKetQuaTCTBXuLyChanged();
    partial void OnCapTrenXuLyChanging(bool value);
    partial void OnCapTrenXuLyChanged();
    partial void OnNgayCapTrenXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapTrenXuLyChanged();
    partial void OnKetQuaCapTrenXuLyChanging(string value);
    partial void OnKetQuaCapTrenXuLyChanged();
    partial void OnThoiGianLapPhieuChanging(System.Nullable<int> value);
    partial void OnThoiGianLapPhieuChanged();
    partial void OnDaLapPhieuChanging(bool value);
    partial void OnDaLapPhieuChanged();
    partial void OnSoPhieuChanging(System.Nullable<decimal> value);
    partial void OnSoPhieuChanged();
    partial void OnNgayLapPhieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapPhieuChanged();
    partial void OnPhieuDuocKyChanging(bool value);
    partial void OnPhieuDuocKyChanged();
    partial void OnHieuLucKyChanging(string value);
    partial void OnHieuLucKyChanged();
    partial void OnDotLapPhieuChanging(string value);
    partial void OnDotLapPhieuChanged();
    partial void OnNguoiKyLapPhieuChanging(string value);
    partial void OnNguoiKyLapPhieuChanged();
    partial void OnChucVuLapPhieuChanging(string value);
    partial void OnChucVuLapPhieuChanged();
    partial void OnDaLapCatTamChanging(bool value);
    partial void OnDaLapCatTamChanged();
    partial void OnMaCTCTDBChanging(System.Nullable<decimal> value);
    partial void OnMaCTCTDBChanged();
    partial void OnMaCHDBChanging(System.Nullable<decimal> value);
    partial void OnMaCHDBChanged();
    partial void OnNoiNhanChanging(string value);
    partial void OnNoiNhanChanged();
    partial void OnNguoiKyChanging(string value);
    partial void OnNguoiKyChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnThongBaoDuocKyChanging(bool value);
    partial void OnThongBaoDuocKyChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    partial void OnThuTien_NhanChanging(bool value);
    partial void OnThuTien_NhanChanged();
    partial void OnThuTien_NgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnThuTien_NgayNhanChanged();
    partial void OnThuTien_GhiChuChanging(string value);
    partial void OnThuTien_GhiChuChanged();
    partial void OnDocSo_NhanChanging(bool value);
    partial void OnDocSo_NhanChanged();
    partial void OnDocSo_NgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnDocSo_NgayNhanChanged();
    partial void OnDocSo_GhiChuChanging(string value);
    partial void OnDocSo_GhiChuChanged();
    #endregion
		
		public CTCHDB()
		{
			OnCreated();
		}
		
		[Column(Storage="_MaCTCHDB", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal MaCTCHDB
		{
			get
			{
				return this._MaCTCHDB;
			}
			set
			{
				if ((this._MaCTCHDB != value))
				{
					this.OnMaCTCHDBChanging(value);
					this.SendPropertyChanging();
					this._MaCTCHDB = value;
					this.SendPropertyChanged("MaCTCHDB");
					this.OnMaCTCHDBChanged();
				}
			}
		}
		
		[Column(Storage="_DanhBo", DbType="NVarChar(11)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this.OnDanhBoChanging(value);
					this.SendPropertyChanging();
					this._DanhBo = value;
					this.SendPropertyChanged("DanhBo");
					this.OnDanhBoChanged();
				}
			}
		}
		
		[Column(Storage="_HopDong", DbType="NVarChar(50)")]
		public string HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					this.OnHopDongChanging(value);
					this.SendPropertyChanging();
					this._HopDong = value;
					this.SendPropertyChanged("HopDong");
					this.OnHopDongChanged();
				}
			}
		}
		
		[Column(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[Column(Storage="_Dot", DbType="NVarChar(50)")]
		public string Dot
		{
			get
			{
				return this._Dot;
			}
			set
			{
				if ((this._Dot != value))
				{
					this.OnDotChanging(value);
					this.SendPropertyChanging();
					this._Dot = value;
					this.SendPropertyChanged("Dot");
					this.OnDotChanged();
				}
			}
		}
		
		[Column(Storage="_Ky", DbType="NVarChar(50)")]
		public string Ky
		{
			get
			{
				return this._Ky;
			}
			set
			{
				if ((this._Ky != value))
				{
					this.OnKyChanging(value);
					this.SendPropertyChanging();
					this._Ky = value;
					this.SendPropertyChanged("Ky");
					this.OnKyChanged();
				}
			}
		}
		
		[Column(Storage="_Nam", DbType="NVarChar(50)")]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[Column(Storage="_LyDo", DbType="NVarChar(MAX)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this.OnLyDoChanging(value);
					this.SendPropertyChanging();
					this._LyDo = value;
					this.SendPropertyChanged("LyDo");
					this.OnLyDoChanged();
				}
			}
		}
		
		[Column(Storage="_GhiChuLyDo", DbType="NVarChar(MAX)")]
		public string GhiChuLyDo
		{
			get
			{
				return this._GhiChuLyDo;
			}
			set
			{
				if ((this._GhiChuLyDo != value))
				{
					this.OnGhiChuLyDoChanging(value);
					this.SendPropertyChanging();
					this._GhiChuLyDo = value;
					this.SendPropertyChanged("GhiChuLyDo");
					this.OnGhiChuLyDoChanged();
				}
			}
		}
		
		[Column(Storage="_SoTien", DbType="Int")]
		public System.Nullable<int> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[Column(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[Column(Storage="_TCTBXuLy", DbType="Bit NOT NULL")]
		public bool TCTBXuLy
		{
			get
			{
				return this._TCTBXuLy;
			}
			set
			{
				if ((this._TCTBXuLy != value))
				{
					this.OnTCTBXuLyChanging(value);
					this.SendPropertyChanging();
					this._TCTBXuLy = value;
					this.SendPropertyChanged("TCTBXuLy");
					this.OnTCTBXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_TroNgai", DbType="Bit NOT NULL")]
		public bool TroNgai
		{
			get
			{
				return this._TroNgai;
			}
			set
			{
				if ((this._TroNgai != value))
				{
					this.OnTroNgaiChanging(value);
					this.SendPropertyChanging();
					this._TroNgai = value;
					this.SendPropertyChanged("TroNgai");
					this.OnTroNgaiChanged();
				}
			}
		}
		
		[Column(Storage="_CatTam", DbType="Bit NOT NULL")]
		public bool CatTam
		{
			get
			{
				return this._CatTam;
			}
			set
			{
				if ((this._CatTam != value))
				{
					this.OnCatTamChanging(value);
					this.SendPropertyChanging();
					this._CatTam = value;
					this.SendPropertyChanged("CatTam");
					this.OnCatTamChanged();
				}
			}
		}
		
		[Column(Storage="_NgayXuLy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuLy
		{
			get
			{
				return this._NgayXuLy;
			}
			set
			{
				if ((this._NgayXuLy != value))
				{
					this.OnNgayXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayXuLy = value;
					this.SendPropertyChanged("NgayXuLy");
					this.OnNgayXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_NoiDungXuLy", DbType="NVarChar(MAX)")]
		public string NoiDungXuLy
		{
			get
			{
				return this._NoiDungXuLy;
			}
			set
			{
				if ((this._NoiDungXuLy != value))
				{
					this.OnNoiDungXuLyChanging(value);
					this.SendPropertyChanging();
					this._NoiDungXuLy = value;
					this.SendPropertyChanged("NoiDungXuLy");
					this.OnNoiDungXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_CreateDate_NgayXuLy", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate_NgayXuLy
		{
			get
			{
				return this._CreateDate_NgayXuLy;
			}
			set
			{
				if ((this._CreateDate_NgayXuLy != value))
				{
					this.OnCreateDate_NgayXuLyChanging(value);
					this.SendPropertyChanging();
					this._CreateDate_NgayXuLy = value;
					this.SendPropertyChanged("CreateDate_NgayXuLy");
					this.OnCreateDate_NgayXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_NgayTCTBXuLy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTCTBXuLy
		{
			get
			{
				return this._NgayTCTBXuLy;
			}
			set
			{
				if ((this._NgayTCTBXuLy != value))
				{
					this.OnNgayTCTBXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayTCTBXuLy = value;
					this.SendPropertyChanged("NgayTCTBXuLy");
					this.OnNgayTCTBXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_KetQuaTCTBXuLy", DbType="NVarChar(MAX)")]
		public string KetQuaTCTBXuLy
		{
			get
			{
				return this._KetQuaTCTBXuLy;
			}
			set
			{
				if ((this._KetQuaTCTBXuLy != value))
				{
					this.OnKetQuaTCTBXuLyChanging(value);
					this.SendPropertyChanging();
					this._KetQuaTCTBXuLy = value;
					this.SendPropertyChanged("KetQuaTCTBXuLy");
					this.OnKetQuaTCTBXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_CapTrenXuLy", DbType="Bit NOT NULL")]
		public bool CapTrenXuLy
		{
			get
			{
				return this._CapTrenXuLy;
			}
			set
			{
				if ((this._CapTrenXuLy != value))
				{
					this.OnCapTrenXuLyChanging(value);
					this.SendPropertyChanging();
					this._CapTrenXuLy = value;
					this.SendPropertyChanged("CapTrenXuLy");
					this.OnCapTrenXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_NgayCapTrenXuLy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCapTrenXuLy
		{
			get
			{
				return this._NgayCapTrenXuLy;
			}
			set
			{
				if ((this._NgayCapTrenXuLy != value))
				{
					this.OnNgayCapTrenXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayCapTrenXuLy = value;
					this.SendPropertyChanged("NgayCapTrenXuLy");
					this.OnNgayCapTrenXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_KetQuaCapTrenXuLy", DbType="NVarChar(MAX)")]
		public string KetQuaCapTrenXuLy
		{
			get
			{
				return this._KetQuaCapTrenXuLy;
			}
			set
			{
				if ((this._KetQuaCapTrenXuLy != value))
				{
					this.OnKetQuaCapTrenXuLyChanging(value);
					this.SendPropertyChanging();
					this._KetQuaCapTrenXuLy = value;
					this.SendPropertyChanged("KetQuaCapTrenXuLy");
					this.OnKetQuaCapTrenXuLyChanged();
				}
			}
		}
		
		[Column(Storage="_ThoiGianLapPhieu", DbType="Int")]
		public System.Nullable<int> ThoiGianLapPhieu
		{
			get
			{
				return this._ThoiGianLapPhieu;
			}
			set
			{
				if ((this._ThoiGianLapPhieu != value))
				{
					this.OnThoiGianLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianLapPhieu = value;
					this.SendPropertyChanged("ThoiGianLapPhieu");
					this.OnThoiGianLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_DaLapPhieu", DbType="Bit NOT NULL")]
		public bool DaLapPhieu
		{
			get
			{
				return this._DaLapPhieu;
			}
			set
			{
				if ((this._DaLapPhieu != value))
				{
					this.OnDaLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._DaLapPhieu = value;
					this.SendPropertyChanged("DaLapPhieu");
					this.OnDaLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_SoPhieu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_NgayLapPhieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapPhieu
		{
			get
			{
				return this._NgayLapPhieu;
			}
			set
			{
				if ((this._NgayLapPhieu != value))
				{
					this.OnNgayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPhieu = value;
					this.SendPropertyChanged("NgayLapPhieu");
					this.OnNgayLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_PhieuDuocKy", DbType="Bit NOT NULL")]
		public bool PhieuDuocKy
		{
			get
			{
				return this._PhieuDuocKy;
			}
			set
			{
				if ((this._PhieuDuocKy != value))
				{
					this.OnPhieuDuocKyChanging(value);
					this.SendPropertyChanging();
					this._PhieuDuocKy = value;
					this.SendPropertyChanged("PhieuDuocKy");
					this.OnPhieuDuocKyChanged();
				}
			}
		}
		
		[Column(Storage="_HieuLucKy", DbType="NVarChar(50)")]
		public string HieuLucKy
		{
			get
			{
				return this._HieuLucKy;
			}
			set
			{
				if ((this._HieuLucKy != value))
				{
					this.OnHieuLucKyChanging(value);
					this.SendPropertyChanging();
					this._HieuLucKy = value;
					this.SendPropertyChanged("HieuLucKy");
					this.OnHieuLucKyChanged();
				}
			}
		}
		
		[Column(Storage="_DotLapPhieu", DbType="NVarChar(50)")]
		public string DotLapPhieu
		{
			get
			{
				return this._DotLapPhieu;
			}
			set
			{
				if ((this._DotLapPhieu != value))
				{
					this.OnDotLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._DotLapPhieu = value;
					this.SendPropertyChanged("DotLapPhieu");
					this.OnDotLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_NguoiKyLapPhieu", DbType="NVarChar(100)")]
		public string NguoiKyLapPhieu
		{
			get
			{
				return this._NguoiKyLapPhieu;
			}
			set
			{
				if ((this._NguoiKyLapPhieu != value))
				{
					this.OnNguoiKyLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NguoiKyLapPhieu = value;
					this.SendPropertyChanged("NguoiKyLapPhieu");
					this.OnNguoiKyLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_ChucVuLapPhieu", DbType="NVarChar(100)")]
		public string ChucVuLapPhieu
		{
			get
			{
				return this._ChucVuLapPhieu;
			}
			set
			{
				if ((this._ChucVuLapPhieu != value))
				{
					this.OnChucVuLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._ChucVuLapPhieu = value;
					this.SendPropertyChanged("ChucVuLapPhieu");
					this.OnChucVuLapPhieuChanged();
				}
			}
		}
		
		[Column(Storage="_DaLapCatTam", DbType="Bit NOT NULL")]
		public bool DaLapCatTam
		{
			get
			{
				return this._DaLapCatTam;
			}
			set
			{
				if ((this._DaLapCatTam != value))
				{
					this.OnDaLapCatTamChanging(value);
					this.SendPropertyChanging();
					this._DaLapCatTam = value;
					this.SendPropertyChanged("DaLapCatTam");
					this.OnDaLapCatTamChanged();
				}
			}
		}
		
		[Column(Storage="_MaCTCTDB", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaCTCTDB
		{
			get
			{
				return this._MaCTCTDB;
			}
			set
			{
				if ((this._MaCTCTDB != value))
				{
					this.OnMaCTCTDBChanging(value);
					this.SendPropertyChanging();
					this._MaCTCTDB = value;
					this.SendPropertyChanged("MaCTCTDB");
					this.OnMaCTCTDBChanged();
				}
			}
		}
		
		[Column(Storage="_MaCHDB", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaCHDB
		{
			get
			{
				return this._MaCHDB;
			}
			set
			{
				if ((this._MaCHDB != value))
				{
					this.OnMaCHDBChanging(value);
					this.SendPropertyChanging();
					this._MaCHDB = value;
					this.SendPropertyChanged("MaCHDB");
					this.OnMaCHDBChanged();
				}
			}
		}
		
		[Column(Storage="_NoiNhan", DbType="NVarChar(MAX)")]
		public string NoiNhan
		{
			get
			{
				return this._NoiNhan;
			}
			set
			{
				if ((this._NoiNhan != value))
				{
					this.OnNoiNhanChanging(value);
					this.SendPropertyChanging();
					this._NoiNhan = value;
					this.SendPropertyChanged("NoiNhan");
					this.OnNoiNhanChanged();
				}
			}
		}
		
		[Column(Storage="_NguoiKy", DbType="NVarChar(100)")]
		public string NguoiKy
		{
			get
			{
				return this._NguoiKy;
			}
			set
			{
				if ((this._NguoiKy != value))
				{
					this.OnNguoiKyChanging(value);
					this.SendPropertyChanging();
					this._NguoiKy = value;
					this.SendPropertyChanged("NguoiKy");
					this.OnNguoiKyChanged();
				}
			}
		}
		
		[Column(Storage="_ChucVu", DbType="NVarChar(100)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[Column(Storage="_ThongBaoDuocKy", DbType="Bit NOT NULL")]
		public bool ThongBaoDuocKy
		{
			get
			{
				return this._ThongBaoDuocKy;
			}
			set
			{
				if ((this._ThongBaoDuocKy != value))
				{
					this.OnThongBaoDuocKyChanging(value);
					this.SendPropertyChanging();
					this._ThongBaoDuocKy = value;
					this.SendPropertyChanged("ThongBaoDuocKy");
					this.OnThongBaoDuocKyChanged();
				}
			}
		}
		
		[Column(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[Column(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[Column(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[Column(Storage="_ThuTien_Nhan", DbType="Bit NOT NULL")]
		public bool ThuTien_Nhan
		{
			get
			{
				return this._ThuTien_Nhan;
			}
			set
			{
				if ((this._ThuTien_Nhan != value))
				{
					this.OnThuTien_NhanChanging(value);
					this.SendPropertyChanging();
					this._ThuTien_Nhan = value;
					this.SendPropertyChanged("ThuTien_Nhan");
					this.OnThuTien_NhanChanged();
				}
			}
		}
		
		[Column(Storage="_ThuTien_NgayNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThuTien_NgayNhan
		{
			get
			{
				return this._ThuTien_NgayNhan;
			}
			set
			{
				if ((this._ThuTien_NgayNhan != value))
				{
					this.OnThuTien_NgayNhanChanging(value);
					this.SendPropertyChanging();
					this._ThuTien_NgayNhan = value;
					this.SendPropertyChanged("ThuTien_NgayNhan");
					this.OnThuTien_NgayNhanChanged();
				}
			}
		}
		
		[Column(Storage="_ThuTien_GhiChu", DbType="NVarChar(MAX)")]
		public string ThuTien_GhiChu
		{
			get
			{
				return this._ThuTien_GhiChu;
			}
			set
			{
				if ((this._ThuTien_GhiChu != value))
				{
					this.OnThuTien_GhiChuChanging(value);
					this.SendPropertyChanging();
					this._ThuTien_GhiChu = value;
					this.SendPropertyChanged("ThuTien_GhiChu");
					this.OnThuTien_GhiChuChanged();
				}
			}
		}
		
		[Column(Storage="_DocSo_Nhan", DbType="Bit NOT NULL")]
		public bool DocSo_Nhan
		{
			get
			{
				return this._DocSo_Nhan;
			}
			set
			{
				if ((this._DocSo_Nhan != value))
				{
					this.OnDocSo_NhanChanging(value);
					this.SendPropertyChanging();
					this._DocSo_Nhan = value;
					this.SendPropertyChanged("DocSo_Nhan");
					this.OnDocSo_NhanChanged();
				}
			}
		}
		
		[Column(Storage="_DocSo_NgayNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> DocSo_NgayNhan
		{
			get
			{
				return this._DocSo_NgayNhan;
			}
			set
			{
				if ((this._DocSo_NgayNhan != value))
				{
					this.OnDocSo_NgayNhanChanging(value);
					this.SendPropertyChanging();
					this._DocSo_NgayNhan = value;
					this.SendPropertyChanged("DocSo_NgayNhan");
					this.OnDocSo_NgayNhanChanged();
				}
			}
		}
		
		[Column(Storage="_DocSo_GhiChu", DbType="NVarChar(MAX)")]
		public string DocSo_GhiChu
		{
			get
			{
				return this._DocSo_GhiChu;
			}
			set
			{
				if ((this._DocSo_GhiChu != value))
				{
					this.OnDocSo_GhiChuChanging(value);
					this.SendPropertyChanging();
					this._DocSo_GhiChu = value;
					this.SendPropertyChanged("DocSo_GhiChu");
					this.OnDocSo_GhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
